name: Publish to NPM
on: push
jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Modules
        run: npm install
      - name: Run type check
        run: npm run types:check
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Build
        run: ./scripts/build.sh
      - name: Copy package jsons to separate react outputs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/setup_all_packages.sh
      - name: Bump Versions of react outputs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/bump_all_versions.sh
      - name: Try Publishing separate react outputs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish_all.sh --access public
