name: Publish to NPM
on: push
jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Modules
        run: npm install
      - name: Run type check
        run: npm run types:check
      - name: Run Linter
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Copy package jsons
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./setup_app_packages.sh
      - name: Bump Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./bump_all_versions.sh
      - name: Separate builds
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./build.sh
      - name: Try Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./publish_all.sh --access public
